version: '2'
services:
    jhipster-app:
        image: jhipster
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://jhipster-postgresql:5432/jhipster
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipster-postgresql:
        extends:
            file: postgresql.yml
            service: jhipster-postgresql
